# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.TextField(default=False),
        ),
    ]
